# Generated by Django 2.2 on 2019-11-01 15:20

from django.db import migrations


def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


def drop_user_profiles(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191101_0536'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles, drop_user_profiles)
    ]
