# Generated by Django 2.2 on 2019-09-26 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190925_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='webapp.Status', verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='webapp.Type', verbose_name='Type'),
            preserve_default=False,
        ),
    ]
