# Generated by Django 2.2 on 2019-10-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of update'),
        ),
    ]
