# Generated by Django 2.2 on 2019-10-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
