# Generated by Django 2.2 on 2019-11-03 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0008_delete_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Start work')),
                ('date_finish', models.DateField(blank=True, null=True, verbose_name='Finish work')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_team', to='webapp.Project', verbose_name='Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_team', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
