# Generated by Django 2.2 on 2019-11-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='date_finish',
            new_name='finish',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='date_start',
            new_name='start',
        ),
    ]
